### ISSUE TITLE
The wording around the cpuTime attribute could use some clarification

### ISSUE THREAD

**Issue by mithro** [WICG/frame-timing#6] opened 2014-10-21 04:27 UTC
The spec currently says;

<blockquote>
cpuTime attribute
<br>
The cpuTime attribute must return a [High Resolution Time] duration giving the total CPU time used to process this frame.
</blockquote>

It is my understanding that the intention is for the cpuTime on the PerformanceMainFrameTiming to include all cpu time spent in the system (including in the compositor and other parts of the system) to get this main frame onto the screen. Is that correct?

It is probably worth adding something like "(best?) estimate of" to the description too?

**Comment by natduca** [comment] 2014-10-21 05:06
Is this dupe of issue #1?

**Comment by igrigorik** [comment] 2014-10-21 05:06
No, I believe the intent is to capture the CPU time of the main + compositor threads only. I.e. same as Chrome Devtools provides on paint + layout events.

**Comment by natduca** [comment] 2014-10-21 05:09
We'll want to have explicit language that gpu-side costs aren't included. But yeah this is a good bug to talk through the details. Sorry bout the incorrect dupage. :)

**Comment by mithro** [comment] 2014-10-21 05:26
Could we also have clear language about this being an _estimate_? Maybe it's implied with any performance metric?

**Comment by igrigorik** [comment] 2014-10-24 17:32
dupe of #1, closing this.

**Closed as completed by igrigorik** 2014-10-24 17:32 UTC
